name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # set your Flutter version

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run analyzer
      - name: Run analyzer
        run: flutter analyze

      # 5. Run tests
      - name: Run tests
        run: flutter test

      # 6. Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload artifact (APK)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
